- name: Deploy ivdev docker env
  hosts: all
  vars:
    docker_registry_url: "{{ lookup('env', 'CI_REGISTRY') }}"
    docker_registry_user: "{{ lookup('env', 'CI_REGISTRY_USER') }}"
    docker_registry_password: "{{ lookup('env', 'CI_REGISTRY_PASSWORD') }}"
    front_image_tag: "{{ lookup('env', 'IMAGE_TAG') }}"
  tasks:
    - name: Change ivsand script permissions
      ansible.builtin.file:
        path: "{{ document_root }}/ivsand"
        mode: '0755'

    - name: Docker login into registry
      community.docker.docker_login:
        registry_url: "{{ docker_registry_url }}"
        username: "{{ docker_registry_user }}"
        password: "{{ docker_registry_password }}"
        reauthorize: false

    - name: Copy docker compose custom config
      ansible.builtin.copy:
        src: docker-compose.custom.yml
        dest: "{{ document_root }}/docker-compose.custom.yml"
        owner: bitrix
        group: bitrix
        mode: '0644'

    - name: Pull Docker images
      ansible.builtin.shell: ./ivsand pull front
      args:
        chdir: "{{ document_root }}"
      environment:
        FRONT_IMAGE_TAG: "{{ front_image_tag }}"

    - name: Run sandbox
      ansible.builtin.shell: ./ivsand start
      args:
        chdir: "{{ document_root }}"
      environment:
        FRONT_IMAGE_TAG: "{{ front_image_tag }}"