# Подключаем шаблоны
include:
  - project: proj/devops/pipelines
    file:
      - front/vue3/dist-build-template.yml
      - front/deploy/dist-deploy-via-ansible-template.yml

stages:
  - build
  - deploy

build:dist:
  extends: .dist_build # Наследуемся от шаблона для сборки
  variables:
    BUILD_IMAGE: "node:22.16.0" # Можно поменять версию ноды
    BUILD_COMMAND: "npm run generate"
    DIST_DIR: "dist" # Папка с dist'ом, которая попадет в артефакты
    FRONT_DIR: "./" # Корневая папка фронта
  only:
    - master # Триггер только на ветку stage

# Через двоеточие указываем название стенда на случай если их будет несколько
deploy:master-front:
  extends: .dist_deploy_via_ansible # Наследуемся от шаблона для деплоя
  variables:
    SSH_HOST: "ivdev.ru"
    SSH_PORT: "2222"
    SSH_USER: "app-mafia"
    REMOTE_DOC_ROOT: "/home/bitrix/www" # Абсолютный путь на сервере до корня с сайтом
    LOCAL_DIST_ROOT: "dist" # Относительный путь к папке с собранным фронтом (из артефактов)
    REMOTE_DIST_PATH: "/" # Путь к папке куда нужно задеплоить собранный фронт (относительно REMOTE_DOC_ROOT)
  needs:
    - job: build:dist
      artifacts: true
  environment:
    name: master-front # Придумываем код для окружения
    url: https://app-mafia.ivdev.ru/ # Указываем адрес
  stage: deploy
  only:
    - master # Если деплоить нужно автоматически, а не руками, то поменять на only: <ветка>

