include:
  - project: proj/devops/pipelines
    file:
      - common/docker/docker-image-build.yml
      - common/ansible/ansible-base-deploy.yml

stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH

build:image-dev:
  extends: .docker_image_build
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master

deploy:dev:
  extends: .ansible_base_deploy
  stage: deploy
  variables:
    PLAYBOOKS: "./playbooks/deploy.yml"
    REMOTE_DOC_ROOT: "/home/bitrix/ext_www/app-nuxt-skeleton-ivdev.ru"
    SSH_USER: "bitrix"
    SSH_HOST: "ivdev.ru"
    SSH_PORT: "22"
  environment:
    name: dev
    url: https://app-nuxt-skeleton.ivdev.ru
  only:
    - master