### Получить список всех items
GET http://localhost:3000/rest/items
Accept: application/json

### Response example:
# [
#   {
#     "id": "123",
#     "name": "Sample item 1",
#     "description": "This is a sample item"
#   },
#   {
#     "id": "456",
#     "name": "Sample item 2",
#     "description": "Another example"
#   }
# ]


### Получить один item по ID
GET http://localhost:3000/rest/items/1
Accept: application/json

### Response example (200 OK):
# {
#   "id": "1",
#   "name": "Sample item 1",
#   "description": "This is a sample item"
# }

### Response example (404 Not Found):
# {
#   "error": "Item not found"
# }
